### ISSUE TITLE
undefined symbol: ASN1_OCTET_STRING_it

### ISSUE THREAD

**Issue by LLLyyy-777** [deadbits/vigil-llm#73]
**Describe the bug**
![image](https://github.com/deadbits/vigil-llm/assets/73068304/98c13480-2321-4dc8-96b9-e545521c7a10)

**To Reproduce**
After installing the project and YARA according to the documentation, the command gives an error

**Expected behavior**
start the Vigil API server

**Environment:**
- Vigil version: 0.8.7
- Python version: 3.10.11
- Operating system: Ubuntu 22.04.2

**Comment by deadbits** [comment]
Hey @LLLyyy-777 , I think this is an issue with the install of the `yara-python` library rather than the project. I ran into something similar early on, but it was resolved by uninstalling yara-python and running `pip install yara-python` again. Try giving that a shot and lmk

**Comment by deadbits** [comment]
Closing this as stale
